"""Topaz script generation and execution for Geode."""

import subprocess
import tempfile
from collections import defaultdict, deque
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

from packaging.specifiers import SpecifierSet
from packaging.version import Version

from geode import __version__
from geode.errors import TopazError
from geode.manifest import load_manifest
from geode.models import Lockfile, Manifest, ResolvedPackage
from geode.cache import get_dep_path, tonel_output_path
from geode.errors import TonelError
from geode.tonel import (
    has_forward_class_refs,
    parse_and_order_tonel,
    transpile_directory,
)
from geode.filetree import transpile_filetree_package, discover_filetree_packages


def generate_install_script(
    project_root: Path,
    manifest: Manifest,
    lockfile: Lockfile,
    stone_name: str,
    user: str = "DataCurator",
    password: str = "swordfish",
    gemstone_version: Optional[str] = None,
    include_dev: bool = False,
    include_tests: bool = False,
    use_tfile: bool = False,
) -> str:
    """Generate a complete Topaz load script."""
    lines: List[str] = []
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # Header
    lines.append(f"! Bootstrap load script generated by Geode {__version__}")
    lines.append(f"! Project: {manifest.package.name} {manifest.package.version}")
    lines.append(f"! Generated: {now}")
    lines.append("")

    # Login
    lines.append(f"set gemstone {stone_name}")
    lines.append(f"set user {user} pass {password}")
    lines.append("login")
    lines.append("")

    # Load dependencies in topological order
    sorted_pkgs = topological_sort(lockfile)
    all_deps = dict(manifest.dependencies)
    if include_dev:
        all_deps.update(manifest.dev_dependencies)

    for pkg in sorted_pkgs:
        dep_path = get_dep_path(project_root, pkg.name)
        dep_manifest = _try_load_dep_manifest(dep_path)
        dep_decl = all_deps.get(pkg.name)

        lines.append(f"! Dependency: {pkg.name} {pkg.version} ({pkg.sha[:12]}...)")

        if dep_manifest:
            # Has its own gemstone.toml — use it
            for f in dep_manifest.load.files:
                lines.append(f"input {dep_path / f}")

            for tonel_dir in dep_manifest.load.tonel:
                src_dir = dep_path / tonel_dir
                if src_dir.is_dir():
                    dest_dir = tonel_output_path(project_root, pkg.name)
                    _emit_tonel_dir(src_dir, dest_dir, use_tfile, lines)

            for ft_pkg in dep_manifest.load.filetree:
                pkg_dir = dep_path / ft_pkg
                if pkg_dir.is_dir():
                    dest_dir = tonel_output_path(project_root, pkg.name)
                    tpz_files = transpile_filetree_package(pkg_dir, dest_dir)
                    for tpz in tpz_files:
                        lines.append(f"input {tpz}")

            if gemstone_version and dep_manifest.load.conditions:
                conditional = evaluate_conditions(
                    dep_manifest.load.conditions, gemstone_version
                )
                for f in conditional:
                    lines.append(f"! GemStone {gemstone_version} conditional")
                    lines.append(f"input {dep_path / f}")

        elif dep_decl and (dep_decl.files or dep_decl.tonel or dep_decl.filetree):
            # No manifest, but consumer declared load overrides
            for f in dep_decl.files:
                lines.append(f"input {dep_path / f}")

            for tonel_dir in dep_decl.tonel:
                src_dir = dep_path / tonel_dir
                if src_dir.is_dir():
                    dest_dir = tonel_output_path(project_root, pkg.name)
                    _emit_tonel_dir(src_dir, dest_dir, use_tfile, lines)

            for ft_pkg in dep_decl.filetree:
                pkg_dir = dep_path / ft_pkg
                if pkg_dir.is_dir():
                    dest_dir = tonel_output_path(project_root, pkg.name)
                    tpz_files = transpile_filetree_package(pkg_dir, dest_dir)
                    for tpz in tpz_files:
                        lines.append(f"input {tpz}")

        else:
            # No manifest, no overrides — auto-discover
            _auto_discover_and_load(
                dep_path, project_root, pkg.name, lines, use_tfile
            )

        lines.append("")

    # Load project's own files
    lines.append(f"! Project: {manifest.package.name}")
    for f in manifest.load.files:
        lines.append(f"input {project_root / f}")

    # Transpile and load project's Tonel directories
    for tonel_dir in manifest.load.tonel:
        src_dir = project_root / tonel_dir
        if src_dir.is_dir():
            dest_dir = tonel_output_path(project_root, manifest.package.name)
            _emit_tonel_dir(src_dir, dest_dir, use_tfile, lines)

    # Transpile and load project's FileTree packages
    for ft_pkg in manifest.load.filetree:
        pkg_dir = project_root / ft_pkg
        if pkg_dir.is_dir():
            dest_dir = tonel_output_path(project_root, manifest.package.name)
            tpz_files = transpile_filetree_package(pkg_dir, dest_dir)
            for tpz in tpz_files:
                lines.append(f"input {tpz}")

    # Conditional files for the project
    if gemstone_version and manifest.load.conditions:
        conditional = evaluate_conditions(
            manifest.load.conditions, gemstone_version
        )
        for f in conditional:
            lines.append(f"! GemStone {gemstone_version} conditional")
            lines.append(f"input {project_root / f}")

    # Dev-dependency files (for test command)
    if include_dev:
        for dep_name in manifest.dev_dependencies:
            dep_path = get_dep_path(project_root, dep_name)
            dep_manifest = _try_load_dep_manifest(dep_path)
            if dep_manifest:
                for f in dep_manifest.load.files:
                    lines.append(f"input {dep_path / f}")

    # Test files
    if include_tests and manifest.test.files:
        lines.append("")
        lines.append(f"! Tests: {manifest.package.name}")
        for f in manifest.test.files:
            lines.append(f"input {project_root / f}")

    lines.append("")
    lines.append("commit")
    lines.append("logout")
    lines.append("exit")

    return "\n".join(lines) + "\n"


def topological_sort(lockfile: Lockfile) -> List[ResolvedPackage]:
    """Sort packages so dependencies come before dependents.

    Uses Kahn's algorithm (BFS-based topological sort).
    """
    if not lockfile.packages:
        return []

    pkg_map: Dict[str, ResolvedPackage] = {p.name: p for p in lockfile.packages}

    # Build in-degree map
    in_degree: Dict[str, int] = {p.name: 0 for p in lockfile.packages}
    # graph: name -> list of packages that depend on it (reverse edges)
    dependents: Dict[str, List[str]] = defaultdict(list)

    for pkg in lockfile.packages:
        for dep_name in pkg.dependencies:
            if dep_name in pkg_map:
                in_degree[pkg.name] = in_degree.get(pkg.name, 0)
                dependents[dep_name].append(pkg.name)
                in_degree[pkg.name] += 1

    # Start with packages that have no dependencies
    queue: deque = deque()
    for name, degree in in_degree.items():
        if degree == 0:
            queue.append(name)

    result: List[ResolvedPackage] = []
    while queue:
        name = queue.popleft()
        result.append(pkg_map[name])
        for dependent in dependents.get(name, []):
            in_degree[dependent] -= 1
            if in_degree[dependent] == 0:
                queue.append(dependent)

    if len(result) != len(lockfile.packages):
        raise TopazError("Circular dependency detected in lockfile")

    return result


def evaluate_conditions(
    conditions: Dict[str, List[str]],
    gemstone_version: Optional[str],
) -> List[str]:
    """Given load conditions and a GemStone version, return additional files to load."""
    if not gemstone_version:
        return []

    try:
        gs_ver = Version(gemstone_version)
    except Exception:
        return []

    files: List[str] = []
    for spec_str, file_list in conditions.items():
        try:
            spec = SpecifierSet(spec_str)
            if gs_ver in spec:
                files.extend(file_list)
        except Exception:
            continue

    return files


def run_topaz(script_content: str, project_root: Path) -> str:
    """Write script to a temp file and execute `topaz -l -s <file>`.

    Returns stdout. Raises TopazError on non-zero exit.
    """
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".topaz", dir=project_root, delete=True
    ) as f:
        f.write(script_content)
        f.flush()

        try:
            result = subprocess.run(
                ["topaz", "-l", "-s", f.name],
                capture_output=True,
                text=True,
                cwd=project_root,
            )
        except FileNotFoundError:
            raise TopazError(
                "topaz is not installed or not in PATH. "
                "Use --dry-run to see the generated script."
            )

        if result.returncode != 0:
            raise TopazError(
                f"Topaz script failed (exit {result.returncode}):\n"
                f"{result.stderr}\n{result.stdout}"
            )

        return result.stdout


def _emit_tonel_dir(
    src_dir: Path,
    dest_dir: Path,
    use_tfile: bool,
    lines: List[str],
) -> None:
    """Emit Topaz directives to load a Tonel directory.

    With ``use_tfile=True``, parses the directory and — if no peer-class
    forward references are detected — emits one ``TFILE`` directive per
    .st file in inheritance order. If forward references are present
    (or parsing fails), falls back to transpiling to a single combined
    .tpz and emitting an ``input`` directive.

    With ``use_tfile=False`` (the default), always transpiles.
    """
    if use_tfile:
        try:
            ordered = parse_and_order_tonel(src_dir)
        except TonelError:
            ordered = []
        if ordered and not has_forward_class_refs(ordered):
            for path, _tc in ordered:
                lines.append(f"TFILE {path}")
            return
        if ordered:
            lines.append(
                f"! TFILE skipped for {src_dir.name}: forward refs detected, "
                "using transpiled .tpz fallback"
            )

    tpz_files = transpile_directory(src_dir, dest_dir)
    for tpz in tpz_files:
        lines.append(f"input {tpz}")


def _try_load_dep_manifest(dep_path: Path) -> Optional[Manifest]:
    """Try to load a dependency's gemstone.toml. Returns None if not found."""
    manifest_path = dep_path / "gemstone.toml"
    if not manifest_path.exists():
        return None
    try:
        return load_manifest(manifest_path)
    except Exception:
        return None


def _auto_discover_and_load(
    dep_path: Path,
    project_root: Path,
    pkg_name: str,
    lines: List[str],
    use_tfile: bool = False,
) -> None:
    """Auto-discover loadable files when a dependency has no manifest and no overrides.

    Searches for Tonel directories (containing .st files) and FileTree
    packages (.package/ dirs), then falls back to .gs files.
    Skips test directories.
    """
    if not dep_path.is_dir():
        return

    found_any = False

    # Recursively find Tonel directories containing .st files
    tonel_dirs: List[Path] = []
    _find_tonel_dirs(dep_path, tonel_dirs)

    if tonel_dirs:
        found_any = True
        for src_dir in tonel_dirs:
            dest_dir = tonel_output_path(project_root, pkg_name)
            _emit_tonel_dir(src_dir, dest_dir, use_tfile, lines)

    # Discover FileTree packages (.package/ dirs)
    ft_pkgs = discover_filetree_packages(dep_path)
    # Filter out test packages
    ft_pkgs = [
        p for p in ft_pkgs
        if not _is_skip_dir(p.stem)  # stem strips .package
    ]

    if ft_pkgs:
        found_any = True
        for pkg_dir in ft_pkgs:
            dest_dir = tonel_output_path(project_root, pkg_name)
            tpz_files = transpile_filetree_package(pkg_dir, dest_dir)
            for tpz in tpz_files:
                lines.append(f"input {tpz}")

    if found_any:
        return

    # Fall back to .gs files (recursive, skipping test dirs)
    gs_files = sorted(dep_path.rglob("*.gs"))
    gs_files = [
        f for f in gs_files
        if not any(_is_skip_dir(part) for part in f.relative_to(dep_path).parts[:-1])
    ]
    for f in gs_files:
        lines.append(f"input {f}")


def _is_skip_dir(name: str) -> bool:
    """Check if a directory name should be skipped during auto-discovery."""
    lower = name.lower()
    if lower in ("tests", "test"):
        return True
    if lower.startswith("."):
        return True
    if lower.endswith("-tests") or lower.endswith("-test"):
        return True
    # Skip FileTree internal directories to prevent misidentifying
    # instance/*.st method files as Tonel directories
    if name.endswith((".package", ".class", ".extension")):
        return True
    return False


def _find_tonel_dirs(root: Path, result: List[Path]) -> None:
    """Recursively find directories containing .st files, skipping test dirs."""
    for child in sorted(root.iterdir()):
        if not child.is_dir():
            continue
        if _is_skip_dir(child.name):
            continue
        if any(child.glob("*.st")):
            result.append(child)
        else:
            _find_tonel_dirs(child, result)
