"""Parse and write gemstone.lock files."""

from pathlib import Path
from typing import Optional

import tomlkit

from gspm.errors import LockfileError
from gspm.models import Lockfile, ResolvedPackage


LOCKFILE_HEADER = """\
# This file is automatically generated by gspm.
# Do not edit it manually. Commit it to version control.

"""


def load_lockfile(path: Path) -> Lockfile:
    """Parse gemstone.lock into a Lockfile.

    Returns an empty Lockfile if the file doesn't exist.
    """
    if not path.exists():
        return Lockfile()

    try:
        doc = tomlkit.loads(path.read_text())
    except Exception as e:
        raise LockfileError(f"Invalid TOML in {path}: {e}") from e

    packages = []
    for entry in doc.get("package", []):
        for field in ("name", "version", "source", "sha"):
            if field not in entry:
                raise LockfileError(f"Missing field '{field}' in lockfile entry")
        packages.append(
            ResolvedPackage(
                name=entry["name"],
                version=entry["version"],
                source=entry["source"],
                sha=entry["sha"],
                dependencies=list(entry.get("dependencies", [])),
            )
        )

    return Lockfile(packages=packages)


def save_lockfile(lockfile: Lockfile, path: Path) -> None:
    """Write a Lockfile to gemstone.lock."""
    doc = tomlkit.document()
    doc.add(tomlkit.comment("This file is automatically generated by gspm."))
    doc.add(tomlkit.comment("Do not edit it manually. Commit it to version control."))
    doc.add(tomlkit.nl())

    aot = tomlkit.aot()
    for pkg in lockfile.packages:
        table = tomlkit.table()
        table.add("name", pkg.name)
        table.add("version", pkg.version)
        table.add("source", pkg.source)
        table.add("sha", pkg.sha)
        if pkg.dependencies:
            table.add("dependencies", pkg.dependencies)
        aot.append(table)

    doc.add("package", aot)
    path.write_text(tomlkit.dumps(doc))
